server:
  servlet:
    context-path: /
  port: 8080

spring:
  application:
    name: kafka

kafka:
  properties:
    bootstrap-servers: localhost:9092
    schema-registry-url: http://localhost:8081
    avro-topic: CUSTOMERTOPIC
